services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/app
      - dev_venv:/app/.venv
      - dev_web:/app/.web
    command: reflex run --loglevel info

volumes:
  dev_venv:
  dev_web:
